name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set version
        run: |
          sed -i "s/0.0.0/${GITHUB_REF:11}/" ./fastapi_startup/__init__.py
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Create cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-publish
          path: ${{ env.pythonLocation }}
      - name: Install Flit
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install flit
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          flit install --symlink
      - name: Publish
        env:
          FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: |
          flit publish
