name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test
          path: ${{ env.pythonLocation }}
      - name: Install Flit
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install flit
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          flit install --symlink
      - name: Lint
        run: |
          black --check ./fastapi_startup ./tests
          isort --check-only ./fastapi_startup ./tests
      - name: Test
        run: |
          pytest -v ./tests
